<a href="https://colab.research.google.com/github/SantanuWorks/SantanuWorks/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic Libraries:

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu118


Tensors: Represents multi-dimensional set of numbers

In [4]:
## Creating Tensors - using torch.Tensor()
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# dimensions of scalar

scalar.ndim

0

In [6]:
# get tensor value as int

scalar.item()

7

In [11]:
# Vector

vector = torch.tensor( [7, 7 ] )
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [12]:
# Create a matrix

mat = torch.tensor(
    [ [1, 2],
    [3, 4] ]
)

print(mat)
print(mat.ndim)
print(mat.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [14]:
# creating a tensor

ten = torch.tensor(
    [ [ [1, 2],
    [3, 4] ],
      [ [5, 6],
    [7, 8] ]
    ]
)

print(ten)
print(ten.ndim)
print(ten.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])
